# Generated by Django 4.2.1 on 2023-06-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_category_updated_at_alter_product_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ription',
        ),
    ]
